apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-volume-pvc-hostpath
spec:
  storageClassName: mycustomclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi