apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv-hostpath-standby
  labels:
    type: local
spec:
  storageClassName: mycustomclass2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/standby"